#!/usr/bin/env python3
"""
Auto-generate project inventory and manifest.

Scans the projects/ folder, writes a manifest.json, and regenerates inventory
sections in README.md and notes.md between special markers.

Markers expected in:
  - projects/README.md
  - projects/notes.md

Inventory block format:
  <!-- BEGIN INVENTORY -->
  ... autogenerated content ...
  <!-- END INVENTORY -->
"""

from __future__ import annotations

import argparse
import ast
import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

BEGIN = "<!-- BEGIN INVENTORY -->"
END = "<!-- END INVENTORY -->"


@dataclass
class FileEntry:
    path: str
    kind: str
    size_bytes: int
    mtime_iso: str
    summary: str
    usage: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "path": self.path,
            "kind": self.kind,
            "size_bytes": self.size_bytes,
            "mtime_iso": self.mtime_iso,
            "summary": self.summary,
            "usage": self.usage,
        }


def _mtime_iso(p: Path) -> str:
    return datetime.fromtimestamp(p.stat().st_mtime).isoformat(timespec="seconds")


def _read_text(p: Path) -> str:
    # Read as UTF-8 without BOM for consistency; errors replaced to avoid crashes
    return p.read_text(encoding="utf-8", errors="replace")


def _write_text(p: Path, s: str) -> None:
    # Write without BOM for cross-platform compatibility
    p.write_text(s, encoding="utf-8", newline="\n")


def _kind_for(path: Path) -> str:
    if path.is_dir():
        return "dir"
    ext = path.suffix.lower()
    if ext == ".py":
        return "python"
    if ext in (".sh", ".bash"):
        return "shell"
    if ext in (".md",):
        return "markdown"
    if ext in (".json",):
        return "json"
    if ext in (".yml", ".yaml"):
        return "yaml"
    if ext in (".txt",):
        return "text"
    return "file"


def _first_line(s: str) -> str:
    for line in s.splitlines():
        line = line.strip()
        if line:
            return line
    return ""


def _py_docstring_summary_and_usage(py_path: Path) -> tuple[str, str]:
    """
    Extract:
      - summary: first non-empty line of module docstring (or empty)
      - usage: a "Usage:" line if present in docstring (including following line if needed)
    """
    try:
        src = _read_text(py_path)
        mod = ast.parse(src)
        doc = ast.get_docstring(mod) or ""
    except Exception:
        return ("", "")

    summary = _first_line(doc)

    # Improved usage extraction: look for "Usage:" line and take the rest of that line,
    # or the next non-empty line if the "Usage:" line is alone.
    usage = ""
    lines = doc.splitlines()
    for i, line in enumerate(lines):
        line_stripped = line.strip()
        if line_stripped.lower().startswith("usage:"):
            # If there is content after "Usage:" on same line
            rest = line_stripped[6:].strip()
            if rest:
                usage = "Usage: " + rest
                break
            # Otherwise, look at next non-empty line
            for next_line in lines[i + 1 :]:
                next_stripped = next_line.strip()
                if next_stripped:
                    usage = "Usage: " + next_stripped
                    break
            break

    return (summary, usage)


def _shell_header_summary_and_usage(sh_path: Path) -> tuple[str, str]:
    """
    For shell scripts, grab initial comment lines (starting with #) as summary,
    and a "Usage:" line if present.
    """
    text = _read_text(sh_path)
    summary = ""
    usage = ""
    for line in text.splitlines()[:40]:
        ls = line.strip()
        if ls.startswith("#!"):
            continue
        if ls.startswith("#"):
            content = ls.lstrip("#").strip()
            if content and not summary:
                summary = content
            if content.lower().startswith("usage:") and not usage:
                usage = "Usage: " + content[len("usage:") :].strip()
        else:
            # stop when real code begins
            if summary or usage:
                break
    return (summary, usage)


def _default_usage(path_from_root: str) -> str:
    # Provide a sensible default command
    if path_from_root.endswith(".py"):
        return f"Usage: python {path_from_root} --help"
    if path_from_root.endswith(".sh"):
        return f"Usage: bash {path_from_root}"
    return ""


def _is_ignored(rel_path: str, gitignore_patterns: list[str]) -> bool:
    """Check if rel_path matches any gitignore pattern."""
    from fnmatch import fnmatch

    for pattern in gitignore_patterns:
        pattern = pattern.strip()
        if not pattern or pattern.startswith("#"):
            continue
        # Simple fnmatch for now; could use pathspec for full gitignore support
        if (
            fnmatch(rel_path, pattern)
            or fnmatch(rel_path, f"*/{pattern}")
            or fnmatch(rel_path, f"{pattern}/*")
        ):
            return True
        # Handle directories
        if pattern.endswith("/") and rel_path.startswith(pattern[:-1]):
            return True
    return False


def scan_projects(projects_dir: Path) -> list[FileEntry]:
    entries: list[FileEntry] = []

    # Load .gitignore patterns
    gitignore_path = projects_dir / ".gitignore"
    gitignore_patterns = []
    if gitignore_path.exists():
        gitignore_patterns = gitignore_path.read_text().splitlines()

    # Exclusions: generator artifacts + caches; also exclude notes.md to avoid self-reference
    exclude_names = {
        "__pycache__",
        ".DS_Store",
        ".git",
    }
    exclude_files = {
        "manifest.json",
        "notes.md",  # exclude from inventory to avoid self-reference
    }

    for p in sorted(projects_dir.rglob("*")):
        rel = p.relative_to(projects_dir).as_posix()
        if any(part in exclude_names for part in p.parts):
            continue
        if p.is_dir():
            continue
        if p.name in exclude_files:
            continue
        if _is_ignored(rel, gitignore_patterns):
            continue

        kind = _kind_for(p)
        summary = ""
        usage = ""

        if kind == "python":
            summary, usage = _py_docstring_summary_and_usage(p)
        elif kind == "shell":
            summary, usage = _shell_header_summary_and_usage(p)

        # Fallbacks
        if not summary:
            summary = ""
        if not usage:
            usage = _default_usage(f"projects/{rel}")

        entries.append(
            FileEntry(
                path=f"projects/{rel}",
                kind=kind,
                size_bytes=p.stat().st_size,
                mtime_iso=_mtime_iso(p),
                summary=summary,
                usage=usage,
            )
        )

    return entries


def render_inventory_md(entries: list[FileEntry]) -> str:
    lines: list[str] = []
    lines.append("## Inventory of Project Utilities")
    lines.append("")
    lines.append("| File | Type | Description | How to run |")
    lines.append("|------|------|-------------|------------|")

    for e in entries:
        desc = e.summary if e.summary else "(no summary yet)"
        run = e.usage if e.usage else ""
        lines.append(f"| `{e.path}` | {e.kind} | {desc} | {run} |")

    lines.append("")
    lines.append(f"_Generated: {datetime.now().isoformat(timespec='seconds')}_")
    return "\n".join(lines)


def _strip_generated_line(block_md: str) -> str:
    """Remove volatile generation timestamp lines before comparisons."""
    lines = [
        line
        for line in block_md.strip().splitlines()
        if not line.startswith("_Generated:")
    ]
    return "\n".join(lines).strip()


def _inventory_block(text: str) -> str:
    if BEGIN not in text or END not in text:
        return ""
    _, rest = text.split(BEGIN, 1)
    block, _ = rest.split(END, 1)
    return block


def _stable_manifest_files(entries: list[FileEntry]) -> list[dict[str, str]]:
    """Return manifest fields that should remain stable across machines/runs."""
    return [
        {
            "path": entry.path,
            "kind": entry.kind,
            "summary": entry.summary,
            "usage": entry.usage,
        }
        for entry in entries
    ]


def check_generated_outputs(
    projects_dir: Path, entries: list[FileEntry], inventory_md: str
) -> int:
    """Validate generated files without rewriting timestamp-bearing artifacts."""
    errors: list[str] = []
    expected_inventory = _strip_generated_line(inventory_md)

    for target in (projects_dir / "README.md", projects_dir / "notes.md"):
        if not target.exists():
            errors.append(f"missing generated inventory target: {target.name}")
            continue
        actual_inventory = _strip_generated_line(_inventory_block(_read_text(target)))
        if actual_inventory != expected_inventory:
            errors.append(
                f"{target.name} inventory is out of date; run python generate_readme.py"
            )

    manifest_path = projects_dir / "manifest.json"
    if not manifest_path.exists():
        errors.append("manifest.json is missing; run python generate_readme.py")
    else:
        try:
            manifest = json.loads(_read_text(manifest_path))
            actual_files = manifest.get("files", [])
        except json.JSONDecodeError as exc:
            errors.append(f"manifest.json is invalid JSON: {exc}")
        else:
            stable_actual = [
                {
                    "path": item.get("path", ""),
                    "kind": item.get("kind", ""),
                    "summary": item.get("summary", ""),
                    "usage": item.get("usage", ""),
                }
                for item in actual_files
            ]
            if stable_actual != _stable_manifest_files(entries):
                errors.append(
                    "manifest.json file inventory is out of date; run python generate_readme.py"
                )

    if errors:
        for error in errors:
            print(f"[error] {error}")
        return 1

    print("✅ Generated inventory and manifest are up to date.")
    return 0


def replace_block(text: str, block_md: str) -> str:
    if BEGIN not in text or END not in text:
        # If markers don't exist, append them
        return text.rstrip() + "\n\n" + BEGIN + "\n" + block_md + "\n" + END + "\n"

    before, rest = text.split(BEGIN, 1)
    _, after = rest.split(END, 1)
    return before.rstrip() + "\n\n" + BEGIN + "\n" + block_md + "\n" + END + after


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate or validate project inventory files."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate README.md, notes.md, and manifest.json without rewriting files.",
    )
    args = parser.parse_args()

    projects_dir = Path(__file__).resolve().parent
    root_dir = projects_dir.parent

    entries = scan_projects(projects_dir)
    inventory_md = render_inventory_md(entries)

    if args.check:
        return check_generated_outputs(projects_dir, entries, inventory_md)

    manifest_path = projects_dir / "manifest.json"
    manifest = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "root": str(root_dir),
        "files": [e.to_dict() for e in entries],
    }
    _write_text(manifest_path, json.dumps(manifest, indent=2, ensure_ascii=True) + "\n")

    # Update README.md and notes.md inside projects/
    for target in (projects_dir / "README.md", projects_dir / "notes.md"):
        if target.exists():
            original = _read_text(target)
            updated = replace_block(original, inventory_md)
            _write_text(target, updated)

    print("✅ README.md and notes.md inventory have been regenerated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
